### ISSUE TITLE
TODO: Implement for generate repo/step

### ISSUE THREAD

**Issue by jrg72** [eropple/auster#1]
diracshard@megamaker ~/Source $ ~/.gem/ruby/2.4.0/bin/auster generate repo
/home/diracshard/.gem/ruby/2.4.0/gems/auster-0.3.1/lib/cfer/auster/cli/generate/repo.rb:21:in `block (2 levels) in generate_repo': TODO: implement (RuntimeError)
        from /home/diracshard/.gem/ruby/2.4.0/gems/cri-2.8.0/lib/cri/command.rb:319:in `run_this'
        from /home/diracshard/.gem/ruby/2.4.0/gems/cri-2.8.0/lib/cri/command.rb:264:in `run'
        from /home/diracshard/.gem/ruby/2.4.0/gems/cri-2.8.0/lib/cri/command.rb:282:in `run'
        from /home/diracshard/.gem/ruby/2.4.0/gems/cri-2.8.0/lib/cri/command.rb:282:in `run'
        from /home/diracshard/.gem/ruby/2.4.0/gems/auster-0.3.1/lib/cfer/auster/cli.rb:60:in `execute'
        from /home/diracshard/.gem/ruby/2.4.0/gems/auster-0.3.1/bin/auster:8:in `<top (required)>'
        from /home/diracshard/.gem/ruby/2.4.0/bin/auster:23:in `load'
        from /home/diracshard/.gem/ruby/2.4.0/bin/auster:23:in `<main>'

Want me to try to implement these Ed? :D

**Comment by eropple** [comment]
If you'd like to, go for it - I had an impl floating around (might still on another machine) that I guess tailed off. I'm sure there's a lib or something we can pull in to do it.

Thanks!

**Comment by eropple** [comment]
FYI I've been writing a gem to make this easier, though it's not quite done yet:

https://github.com/eropple/copypasta
